### ISSUE TITLE
New Resource Request

### ISSUE THREAD

**Issue by kievsash** [jsonberry/learn-reactive#11]
## Two options for adding a resource to learnreactive.com

1. Fill out this issue and I (jsonberry) can add it later

### Required Attributes
- origin_title: Tools for RxJS code unit testing in Angular
- author: Oleksandr Poshtaruk (@Ex_extremal)
- cost: false
- tags: rxjs, angular, unit testing
- difficulty: advanced
- format: course
- source: https://mailchi.mp/9c8299ec62c2/rxjsunittesting
.

### Optional Attributes
- social: https://twitter.com/El_Extremal

### Summary
In this course you will learn different tools and methods for rxjs code unit testing in Angular apps.

Jasmine with done callback
VirtualTimeScheduler testing
fakeAsync testing
TestScheduler
TestScheduler.run methods
Marble testing
Jasmine-mables
rxjs-marbles

All examples code will be provided as Angular demo project in a GitHub repo!

**Comment by jsonberry** [comment]
It's live! 2c6721ccf3d7331a498c1631cb3df5034d6f0bec

Thanks for adding :)

**Comment by kievsash** [comment]
Thank you 👍
